image: lemosx/emilua

gcc:
  script:
    - git clone https://gitlab.com/emilua/emilua
    - cd emilua && mkdir build 
    - cd build && CC=gcc meson -D enable_tests=true -Db_sanitize=address -Db_sanitize=pointer-compare  ..
    - ninja
    - meson test
  only:
  - master
gcc:
  image: lemosx/clang-emilua
  script:
    - CC=clang meson --reconfigure -D enable_tests=true -Db_sanitize=address ../
    - ninja
    - meson test



