version: 2.1

jobs:
  prepare:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: brew install luajit git re2c gawk asciidoctor gcc meson ninja fmt boost 
  build_test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: git clone https://gitlab.com/emilua/emilua && python tests/main.py

workflows:
  build_and_test:
    jobs:
      - prepare
      - build_test:
          requires:
            - prepare

